// client/src/App.vue
<script setup lang="ts">
import { RouterLink, RouterView } from "vue-router";
import HelloWorld from "./components/HelloWorld.vue";
import NavVue from "./components/Nav.vue";
</script>

<template>
  <header>
    <NavVue />
  </header>

  <div class="container">
    <RouterView />
  </div>
</template>

<style scoped></style>

// next-app/pages/_app.tsx
import 'bulma';
import '../styles/globals.css'
import type { AppProps } from 'next/app'
import NavVue from '../components/NavBar'

// const NavVue = () => <nav className="navbar is-primary"></nav>


export default function App({ Component, pageProps }: AppProps) {
  return (
    <div className="root">
      <header>
        <NavVue />
      </header>

      <div className="container">
        <Component {...pageProps} />
      </div>
    </div>
  )
}
